### ISSUE TITLE
Decision Tree Error

### ISSUE THREAD

**Issue by kennetham** [serendipious/nodejs-decision-tree-id3#3] opened 2015-10-07 13:02 UTC
There's an error here.

decision-tree.js:20
      root = childNode.child;
                      ^

TypeError: Cannot read property 'child' of undefined
    at Object.ID3.predict (/nodejs-decision-tree-id3-master/lib/decision-tree.js:20:23)
    at Object.<anonymous> (/nodejs-decision-tree-id3-master/example.js:22:34)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by serendipious** [comment] 2015-10-08 06:48
Hi Kenneth, can you provide steps to reproduce the issue?

**Comment by kennetham** [comment] 2015-10-08 07:08
Hi Ankit,

I followed your example after installing. I followed the usage to input the test data and setup for prediction and evaluation.

There I got this error during runtime.

Thanks

**Comment by serendipious** [comment] 2015-10-10 00:48
Hi Kenneth, I am not able to reproduce the issue following the example provided in the README. I was hoping you could provide some more information to help debug this:

1. Which version of the `decision-tree` package are you using?
2. Can you provide the code you are executing to help reproduce the issue?

Thanks!

**Comment by kennetham** [comment] 2015-10-12 04:09
Hi Ankit,
I was using the latest one, I assumed is in your master branch.
The code was the example I followed in your README.md.

**Comment by SummerWish** [comment] 2015-11-01 03:43
I have the same issue here.

Training data:
http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data

Testing data:
http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test

My program:
```js
var DecisionTree = require('decision-tree');
var fs = require('fs');

var features = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country"];
var class_name = "result";

var columnMapping = features.concat(class_name);

function readData(file)
{
  var rows = fs.readFileSync(file).toString().split('\n').filter(function (l) { return l.trim().length > 0; }).map(function (row) {
    var d = {};
    var columns = row.split(', ');
    for (var i = 0; i < columns.length; ++i) {
      d[columnMapping[i]] = columns[i];
    }
    return d;
  });
  return rows;
}

var training_data = readData('./adult.data.txt');
var test_data = readData('./adult.test.txt');

console.log('Building tree...');

var dt = new DecisionTree(training_data, class_name, features);

console.log('Evaluating...');

var accuracy = dt.evaluate(test_data);

console.log('accuracy:');
console.log(accuracy);

console.log('Exporting...');

var treeModel = dt.toJSON();
fs.writeFileSync('./model.json', treeModel);
```

**Comment by Resseguie** [comment] 2015-12-18 02:24
I got the same error as well. Here's a simplified version of what I was attempting:
https://gist.github.com/Resseguie/d145b358200c83c05615

Note it's all numeric and I didn't enter a lot of training data. Don't know if that is related.

I should also point out that I tried the example from the README and it worked fine.

**Comment by Resseguie** [comment] 2015-12-18 02:37
I updated my gist to have random training data as well. It occasionally works and spits out an answer, but usually dies with the error on line 20.

**Comment by scrivna** [comment] 2015-12-19 21:53
I've just commited a fix to this, I wasn't entirely sure it was this logic was the right thing to do in ID3, but I've just looked at a few other libraries implementing this and my fix is how they handle the situation as well, see example... https://github.com/yandongliu/learningjs/blob/master/learningjs.js#L66
It comes from a scenario where testing data hasn't been seen in the training set, so returns the most dominant value up until that point.

**Comment by serendipious** [comment] 2015-12-21 04:17
Thanks @scrivna for contributing a bug fix to this issue! I have merged your pull request.

**Closed by serendipious** 2015-12-21 04:17 UTC
Labels: bug, question
