### ISSUE TITLE
Saving then importing a model gives an error

### ISSUE THREAD

**Issue by mysticaltech** [serendipious/nodejs-decision-tree-id3#22] opened 2021-02-08 21:57 UTC
When saving a model with .toJSON, and later importing it, it generates the following error:

`TypeError: Cannot read property 'length' of undefined`

I triple checked multiple times, this error is very real.

**Comment by serendipious** [comment] 2021-04-03 21:58
Sorry for the delayed response @mysticaltech, and thanks for filing this bug. This might be related to the other bug (#21) you had filed, that is now fixed in the latest release (>= 0.3.4) as I'm unable to reproduce it at least for sample datasets. Would you mind re-testing and see if you are still encountering the issue? Feel free to re-open the issue if you continue to see the bug. Thanks again!

**Closed by serendipious** 2021-04-03 21:58 UTC
